<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.6.4">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.6.4">
   <object array="yes" class="double" name="propertyArray" primitive="yes">
      <object class="double" name="0" primitive="yes">10000.0</object>
      <object class="double" name="1" primitive="yes">1000.0</object>
      <object class="double" name="2" primitive="yes">100.0</object>
      <object class="double" name="3" primitive="yes">10.0</object>
      <object class="double" name="4" primitive="yes">0.01</object>
      <object class="double" name="5" primitive="yes">0.01</object>
      <object class="double" name="6" primitive="yes">0.0010</object>
      <object class="double" name="7" primitive="yes">1.0E-4</object>
      <object class="double" name="8" primitive="yes">1.0E-5</object>
      <object class="double" name="9" primitive="yes">1.0</object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">cv\train-@INDEX@.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">10</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">2</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.meta.FilteredClassifier</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">2</object>
         <object class="java.lang.String" name="13">--</object>
         <object class="java.lang.String" name="14">-F</object>
         <object class="java.lang.String" name="15">weka.filters.supervised.instance.Resample -B 1.0 -S 1 -Z 100.0</object>
         <object class="java.lang.String" name="16">-W</object>
         <object class="java.lang.String" name="17">weka.classifiers.functions.SMO</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-C</object>
         <object class="java.lang.String" name="20">1.0</object>
         <object class="java.lang.String" name="21">-L</object>
         <object class="java.lang.String" name="22">0.0010</object>
         <object class="java.lang.String" name="23">-P</object>
         <object class="java.lang.String" name="24">1.0E-12</object>
         <object class="java.lang.String" name="25">-N</object>
         <object class="java.lang.String" name="26">2</object>
         <object class="java.lang.String" name="27">-V</object>
         <object class="java.lang.String" name="28">-1</object>
         <object class="java.lang.String" name="29">-W</object>
         <object class="java.lang.String" name="30">1</object>
         <object class="java.lang.String" name="31">-K</object>
         <object class="java.lang.String" name="32">weka.classifiers.functions.supportVector.NumericPrecomputedKernelMatrixKernel -M E:\projects\ytex\cmc\weka\cmc-train-gram.matrix</object>
         <object class="java.lang.String" name="33"/>
         <object class="java.lang.String" name="34"/>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.meta.FilteredClassifier</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">2</object>
               <object class="java.lang.String" name="6">--</object>
               <object class="java.lang.String" name="7">-F</object>
               <object class="java.lang.String" name="8">weka.filters.supervised.instance.Resample -B 1.0 -S 1 -Z 100.0</object>
               <object class="java.lang.String" name="9">-W</object>
               <object class="java.lang.String" name="10">weka.classifiers.functions.SMO</object>
               <object class="java.lang.String" name="11">--</object>
               <object class="java.lang.String" name="12">-C</object>
               <object class="java.lang.String" name="13">1.0</object>
               <object class="java.lang.String" name="14">-L</object>
               <object class="java.lang.String" name="15">0.0010</object>
               <object class="java.lang.String" name="16">-P</object>
               <object class="java.lang.String" name="17">1.0E-12</object>
               <object class="java.lang.String" name="18">-N</object>
               <object class="java.lang.String" name="19">2</object>
               <object class="java.lang.String" name="20">-V</object>
               <object class="java.lang.String" name="21">-1</object>
               <object class="java.lang.String" name="22">-W</object>
               <object class="java.lang.String" name="23">1</object>
               <object class="java.lang.String" name="24">-K</object>
               <object class="java.lang.String" name="25">weka.classifiers.functions.supportVector.NumericPrecomputedKernelMatrixKernel -M E:\projects\ytex\cmc\weka\cmc-train-gram.matrix</object>
               <object class="java.lang.String" name="26"/>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.meta.FilteredClassifier" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.supervised.instance.Resample -B 1.0 -S 1 -Z 100.0</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.functions.SMO</object>
               <object class="java.lang.String" name="4">--</object>
               <object class="java.lang.String" name="5">-C</object>
               <object class="java.lang.String" name="6">1.0</object>
               <object class="java.lang.String" name="7">-L</object>
               <object class="java.lang.String" name="8">0.0010</object>
               <object class="java.lang.String" name="9">-P</object>
               <object class="java.lang.String" name="10">1.0E-12</object>
               <object class="java.lang.String" name="11">-N</object>
               <object class="java.lang.String" name="12">2</object>
               <object class="java.lang.String" name="13">-V</object>
               <object class="java.lang.String" name="14">-1</object>
               <object class="java.lang.String" name="15">-W</object>
               <object class="java.lang.String" name="16">1</object>
               <object class="java.lang.String" name="17">-K</object>
               <object class="java.lang.String" name="18">weka.classifiers.functions.supportVector.NumericPrecomputedKernelMatrixKernel -M E:\projects\ytex\cmc\weka\cmc-train-gram.matrix</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="2" primitive="no">
         <object class="weka.classifiers.functions.SMO" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-C</object>
               <object class="java.lang.String" name="1">1.0</object>
               <object class="java.lang.String" name="2">-L</object>
               <object class="java.lang.String" name="3">0.0010</object>
               <object class="java.lang.String" name="4">-P</object>
               <object class="java.lang.String" name="5">1.0E-12</object>
               <object class="java.lang.String" name="6">-N</object>
               <object class="java.lang.String" name="7">2</object>
               <object class="java.lang.String" name="8">-V</object>
               <object class="java.lang.String" name="9">-1</object>
               <object class="java.lang.String" name="10">-W</object>
               <object class="java.lang.String" name="11">1</object>
               <object class="java.lang.String" name="12">-K</object>
               <object class="java.lang.String" name="13">weka.classifiers.functions.supportVector.NumericPrecomputedKernelMatrixKernel -M E:\projects\ytex\cmc\weka\cmc-train-gram.matrix</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.classifiers.meta.FilteredClassifier</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="3" primitive="no">
         <object class="double" name="value" primitive="yes">1.0</object>
         <object class="java.lang.String" name="parentClass">weka.classifiers.functions.SMO</object>
         <object class="java.lang.String" name="property">c</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.CSVResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">cv-r-@INDEX@.csv</object>
      </object>
      <object class="java.io.File" name="outputFile">cv\cv-r-@INDEX@.csv</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
